name: flutter_music_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  just_audio: ^0.9.37
  rxdart: ^0.27.5
  dio: ^5.0.0
  # dio_http_cache_lts: ^0.4.1
  permission_handler: ^9.2.0
  file_picker: ^8.0.0+1
  flutter_downloader: ^1.11.7
  on_audio_query: ^2.9.0
  cupertino_icons: ^1.0.8
  just_audio_background: ^0.0.1-beta.13
  share_plus: ^7.2.2
  speech_to_text: ^6.6.0
  crypto: ^3.0.3
  cookie_jar: ^4.0.0
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/music/
    - assets/image/